spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/test_security?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081

application:
  secret: mySecret